#!/bin/sh
set -e
prog=$(basename "$0")
error() { echo "$1" >&2; exit 1; }
[ -n "$1" ] || error "usage: $prog <expected MD5 hash of STDIN>"
input=$(cat /dev/stdin)
[ "$(echo "$input" | md5sum | cut -d' ' -f1)" = "$1" ] || error "$prog: MD5 hashes do not match"
echo "$input"
